layers:
  entities:
    color: khaki1
    modules:
      - dep_check.models
      - dep_check.dependency_finder
      - dep_check.checker

  use_cases:
    color: red
    modules:
      - dep_check.use_cases

  external:
    color: deepskyblue
    modules:
      - dep_check.infra
      - dep_check.main

bgcolor: lightgray

fold_modules:
  - dep_check.infra

hide_modules:
  - dep_check.models
