---
version: 2.1

########################################################################################
# JOBS
#
# A sequence of steps to be used in workflows, i.e. checking the source code quality
# or deploying the application to a given environment. Jobs are independant. They will
# not run unless used in a workflow.
########################################################################################

jobs:

  # Check the source code quality with various static analysis tools
  static_analysis:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install CircleCI-specific dependencies
          command: |
            sudo apt update
            sudo apt install -y libenchant1c2a
      - run:
          name: Install the project dependencies
          command: make init
      - run:
          name: Run all the linters
          command: make lint

  # Run the unit tests with coverage check, and make sure the integration tests have run
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install CircleCI-specific dependencies
          command: |
            sudo apt update
            sudo apt install -y libenchant1c2a graphviz
      - run:
          name: Install the project dependencies
          command: make init
      - run:
          name: Run the unit tests
          command: |
            source venv/bin/activate && \
            make test
      - store_test_results:
          path: test-results
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - static_analysis
      - test
